package model.subjects;

import model.campus.CampusObject;

public class CampusSubject implements CampusObject {
    private final int id;
    private final String name;

    /**
     * constructor of CampusSubject class
     * @param id subject id in database
     * @param name subject name
     */
    public CampusSubject(int id, String name) {
        this.id = id;
        this.name = name;

    }

    /**
     * override of CampusObjects getId (which this class is implementing)
     * @return id of this subject in database
     */
    @Override
    public int getId() {
        return id;
    }

    /**
     * @return subject name
     */
    public String getName() {
        return name;
    }

    /**
     * override of equals method automatically generated by eclipse
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CampusSubject other = (CampusSubject) obj;
        return id == other.id;
    }
}
