package model.accounts;

import model.campus.CampusObject;

/**
 * Created by Niko on 07.06.2017.
 * <p>
 * The SmartCampus account ADT
 * (immutable)
 */
public class User implements CampusObject {

    private final int userID;
    private final String eMail;
    private final String firstName;
    private final String lastName;
    private final UserStatus status;
    private final UserType userType;
    private final int userRoleId;

    public User(int userID, String eMail, String firstName, String lastName,
                UserStatus status, UserType userType, int userRoleId) {
        this.userID = userID;
        this.eMail = eMail;
        this.firstName = firstName;
        this.lastName = lastName;
        this.status = status;
        this.userType = userType;
        this.userRoleId = userRoleId;
    }

    @Override
    public int getID() {
        return userID;
    }

    public String geteMail() {
        return eMail;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public UserStatus getStatus() {
        return status;
    }

    public UserType getUserType() {
        return userType;
    }

    public int getUserRoleId() {
        return userRoleId;
    }
    
    public enum UserRole {
        STUDENT, LECTURER, STAFF
    }
    
    public enum UserStatus {
        ACTIVE, BANNED
    }

    public enum UserType {
        ADMIN, USER;

        @Override
        public String toString() {
            switch (this) {
                case USER:
                    return "User";
                case ADMIN:
                    return "Administrator";
            }
            return "";
        }
    }
    
    /**
     * override of equals method automatically generated by eclipse
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        User other = (User) obj;
        if (userID != other.userID)
            return false;
        return true;
    }
}
