package model.lectures;

import model.campus.CampusObject;

public class CampusSubject implements CampusObject {
    private final int id;
    private final String name;

    public CampusSubject(int id, String name) {
        this.id = id;
        this.name = name;

    }

    public String getName() {
        return name;
    }

    @Override
    public int getId() {
        return id;
    }
    
    /**
     * override of equals method automatically generated by eclipse
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CampusSubject other = (CampusSubject) obj;
        return id == other.id;
    }
}
