package model.rooms;

import model.campus.CampusObject;

/**
 * Created by Niko on 07.06.2017.
 * <p>
 * The SmartCampus Room ADT (Immutable)
 */
public class Room implements CampusObject {

    private final int roomID;
    private final int capacity;
    private final String roomName;
    private final RoomType roomType;
    private final SeatType seatType;
    private final boolean isAvailableForStudents;
    private final int floor;

    /**
     * Constructs a new Room object.
     * @param roomID room id in the database
     * @param capacity room capacity (number of seats)
     * @param roomName room name (mostly number)
     * @param roomType room type
     * @param seatType room seat type
     * @param isAvailableForStudents if the room can be booked by a student
     * @param floor room floor
     */
    public Room(int roomID, int capacity, String roomName, RoomType roomType,
                SeatType seatType, boolean isAvailableForStudents, int floor) {
        this.roomID = roomID;
        this.capacity = capacity;
        this.roomName = roomName;
        this.roomType = roomType;
        this.seatType = seatType;
        this.isAvailableForStudents = isAvailableForStudents;
        this.floor = floor;
    }

    /**
     * override of CampusObjects getId (which this class is implementing)
     * @return id of this room in database
     */
    @Override
    public int getId() {
        return roomID;
    }

    /**
     * @return room floor
     */
    public int getFloor() {
        return floor;
    }

    /**
     * @return if this room can be booked by a student
     */
    public boolean isAvailableForStudents() {
        return isAvailableForStudents;
    }

    /**
     * @return room capacity
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * @return room name (number)
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * @return room type
     */
    public RoomType getRoomType() {
        return roomType;
    }

    /**
     * @return room seat type
     */
    public SeatType getSeatType() {
        return seatType;
    }

    /**
     * override of equals method automatically generated by eclipse
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Room other = (Room) obj;
        if (roomID != other.roomID)
            return false;
        return true;
    }

    @Override
    public String toString() {
        return getRoomName();
    }

    /**
     * enum for room type
     */
    public enum RoomType {
        AUDITORIUM, UTILITY, LABORATORY
    }

    /**
     * enum for seat type
     */
    public enum SeatType {
        DESKS, CHAIRS, COMPUTERS, TABLES
    }
}
